ktor:
    application:
        modules:
            - ktor.ApplicationKt.module
    deployment:
        port: 8081
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password