ktor:
  application:
    modules:
      - ktor.ApplicationKt.module
  deployment:
    port: 8081
    host: "localhost"  # ip del servidor
  database:
    url: "jdbc:mariadb://localhost:3306/dbEmployee"
    driver: "org.mariadb.jdbc.Driver"
    username: "josema"
    password: "josema"