package domain.models.enums

enum class Sport {
    ATHLETICS, SWIMMING, GYMNASTICS, BASKETBALL, FOOTBALL, TENNIS,
    BOXING, CYCLING, WRESTLING, WEIGHTLIFTING, FENCING, ROWING,
    ARCHERY, JUDO, BADMINTON, HANDBALL, VOLLEYBALL, TABLE_TENNIS,
    TAEKWONDO, SHOOTING
}